primercommit
wolox-training/sl-javascript-cypress pull request #1
Opened 2020-12-29 18:25 UTC by smlopez88

**Summary**:
New tests added for the CF01 Sign Up User Story

- empty-fields-errors.js: a test for each field (username, email, password)
- existing-user.js: three tests (repeated email and username, repeated email, repeated username)
- password-validations.js: three tests (password with less than 8 characters, password with blank spaces, deleted password)
- email-validations.js: two tests (existing email, email with no @ )
- successful-signup.js one test (happy signup path)

**Screenshots:**

![PR](https://user-images.githubusercontent.com/73854403/103305441-eac63d00-49e9-11eb-9519-eecead53b0a9.png)

![cypress](https://user-images.githubusercontent.com/73854403/103305454-f44fa500-49e9-11eb-9bee-eb9d7403073a.png)

2020-12-30 16:36 UTC, eledwinn requested changes

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +        cy.visit('https://qa-angular-conduit.vercel.app/register');
Add base url in cypress.json file.
https://docs.cypress.io/guides/references/configuration.html#Options
And in this line, only use `cy.visit('register');`

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +        cy.wait(6000);
Why need this wait after each?

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +const { expect } = require("chai");
Use two spaces as indent configuration please

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +        })
Indent this line please

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +    it('Existing Email',function(){
Add white space after comma, and after `()` 😃

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +        cy.get(':nth-child(1) > .form-control').type('sml0pez88');
Try find a better selector, like id, name or another attribute. (only if possible)

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +
Remove empty line

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +    it ('No @',function(){
Add white space after comma and after `()`

2020-12-30 16:36 UTC, eledwinn commented on CF01/email-validations.js
> +
Only one empty line please

2020-12-30 16:36 UTC, eledwinn commented on CF01/empty-fields-error.js
> +        cy.visit('https://qa-angular-conduit.vercel.app/register');
Use baseUrl :)

2020-12-30 16:36 UTC, eledwinn commented on CF01/empty-fields-error.js
> +    afterEach(function() {
Empty line between each function

2020-12-30 16:36 UTC, eledwinn commented on CF01/empty-fields-error.js
> +            if (cy.get('.btn').should('have.attr','disabled')==false) {
did you test this? I think the .should method doesn't work as you expect. 
try to test for both cases to make sure it works please.

2020-12-30 16:36 UTC, eledwinn commented on CF01/empty-fields-error.js
> +
Remove empty lines between internal blocks

2020-12-30 16:36 UTC, eledwinn commented on CF01/empty-fields-error.js
> +})
Always add empty line at end of files

2020-12-30 16:36 UTC, eledwinn commented on CF01/password-validations.js
> +    afterEach(function() {
Empty line between functions

2020-12-30 16:36 UTC, eledwinn commented on CF01/successful-signup.js
> +        cy.wait(6000);
Avoid use `cy.wait`, if you need wait for next command, use selector timeout.
```js
cy.get(':nth-child(4) > .nav-link', { timeout: 6000 })
```

2021-01-07 15:39 UTC, smlopez88 commented
All changes added in second commit.

2021-01-07 15:39 UTC, merged